server:
  port: 8080 # 应用启动端口号
  servlet:
    session:
      timeout: 5m # 会话超时时间，设置为 5 分钟
  compression:
    enabled: true # 启用响应压缩，提高传输效率
    min-response-size: 2KB # 压缩的最小响应体大小，超过该值才压缩

spring:
  application:
    name: bytelogs # 应用名称，用于服务发现或日志标识
  config:
    import: 
      - application-dal.yml # 引入数据库相关配置文件
      - application-mq.yml # 引入消息队列相关配置文件
      - application-ai.yml # 引入AI服务相关配置文件

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 数据库字段下划线命名自动映射为 Java 驼峰命名

database:
  name: byte_logs # 自定义字段，数据库名称（可用于多数据源识别）

jwt:
  issuer: bytelogs # JWT 令牌发布者标识
  secret: your-very-secure-and-long-secret-key-by-bytelogs # JWT 加密用的密钥，必须保密
  default-expire: 1d # 默认有效时间
  keep-login-expire: 3d # 保持登录有效时间

user:
  default-password: bytelogs@123

# 应用级配置
app:
  exception:
    print-stack-trace: true # 是否打印异常调用栈信息，开发环境建议true，生产环境建议false